<?php

/**
 * @file
 * Contains josh_paragraphs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\views\ViewExecutable;

// @todo
// - Don't hardcode these here but rather use an info hook, yaml file, managed
//   configuration, State API, etc. Or grab them directly from the styleguide
//   component's JSON files!
// - Make sure the "help" text gets translated.
const KALAGRAPHS_TYPES = [

  // Molecules.
  'article__image_featured' => [
    'title' => 'Image - Featured',
    'path' => '@molecules',
    'fields' => [
      'image',
      'text',
    ],
    'help' => 'Leave the Image field empty if you want to use the News featured image.',
  ],
  'callout' => [
    'title' => 'Callout',
    'path' => '@molecules',
    'fields' => [
      'text',
    ],
  ],
  'tout--cta' => [
    'title' => 'CTA Tout',
    'path' => '@molecules',
    'fields' => [
      'title',
      'text',
      'image',
      'links',
    ],
  ],
  'testimonial' => [
    'title' => 'Testimonial',
    'path' => '@molecules',
    'is_subcomponent' => FALSE,
    'fields' => [
      'text',
      'image',
      'subtitle',
    ],
    'help' => 'Use the subtitle field for quote attribution',
  ],
  'hero' => [
    'title' => 'Hero',
    'path' => '@molecules',
    'fields' => [
      'title',
      'subtitle',
      'text',
      'image',
      'links',
    ],
    'bundles' => ['kalagraphs_component'],
  ],
  'text' => [
    'title' => 'Simple Text',
    'template' => 'layout--1-up',
    'path' => '@layouts',
    'is_subcomponent' => FALSE,
    'fields' => [
      'text',
    ],
  ],
];

/**
 * Implements hook_help().
 */
function josh_paragraphs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the josh_paragraphs module.
    case 'help.page.josh_paragraphs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Customisations for Paragraphs and Kalagraphs functionality on Josh\'s website.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function josh_paragraphs_theme() {

  // First, manually create some theme hooks for certain atoms.
  //
  // @todo Don't hardcode these here but rather use an info hook, yaml file,
  // managed configuration, State API, etc. Or grab them directly from the
  // styleguide component's JSON files!
  //
  // @see \Drupal\kalagraphs\Plugin\Field\FieldFormatter\KalagraphsLinkFormatter
  // @see \Drupal\kalagraphs\Plugin\Field\FieldFormatter\KalagraphsImageFormatter
  $items['kalastatic__link'] = [
    'template' => 'link',
    'path' => '@atoms/link',
    'variables' => [
      'url' => '',
      'text' => '',
      'class' => '',
    ],
  ];
  $items['kalastatic__link__icon'] = [
    'template' => 'link--icon',
    'path' => '@atoms/link--icon',
    'variables' => [
      'url' => '',
      'text' => '',
      'class' => '',
    ],
  ];
  $items['kalastatic__image'] = [
    'template' => 'image',
    'path' => '@atoms/image',
    'variables' => [
      'uri' => '',
      'alt' => '',
      'title' => '',
      'class' => '',
      'width' => '',
      'height' => '',
    ],
  ];
  $items['kalastatic__image__bg'] = [
    'template' => 'image__bg',
    'path' => '@atoms/image__bg',
    'variables' => [
      'uri' => '',
      'alt' => '',
      'height' => '',
    ],
  ];
  return $items;
}

/**
 * Implements hook_preprocess_hook() for paragraph__kalagraphs_component__default().
 */
function josh_paragraphs_preprocess_paragraph__kalagraphs_component__default(&$vars) {
  $paragraph = $vars['paragraph'];
  $type = $paragraph->field_kalagraphs_type->value;
  switch ($type) {
    case 'article__image_featured':
      $vars['class'][] = 'featured';
      break;

    case 'testimonial':
      // We have to misuse the subtitle field to store the attribution.
      if (isset($vars['subtitle'])) {
        $vars['attribution'] = $vars['subtitle'];
      }
      break;

    case 'text__no_wrapper':
      $vars['content']['field_kalagraphs_text'] = [
        '#type' => 'container',
        'text' => $vars['content']['field_kalagraphs_text'],
      ];
  }
}

/**
 * Implements hook_preprocess_hook() for image().
 */
function sod_paragraphs_preprocess_image(&$vars) {
  // Manually set the width and height from the attributes array because our
  // image template can't handle an attributes array just yet.
  $vars['width'] = $vars['attributes']['width'];
  $vars['height'] = $vars['attributes']['height'];
}
